src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClienteRepository::class)
 */
class Cliente
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $ci_ruc;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $razon_social;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telefono;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $direccion;

    /**
     * @ORM\OneToMany(targetEntity=Factura::class, mappedBy="cliente")
     */
    private $facturas;

    public function __construct()
    {
        $this->facturas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCiRuc(): ?string
    {
        return $this->ci_ruc;
    }

    public function setCiRuc(string $ci_ruc): self
    {
        $this->ci_ruc = $ci_ruc;

        return $this;
    }

    public function getRazonSocial(): ?string
    {
        return $this->razon_social;
    }

    public function setRazonSocial(string $razon_social): self
    {
        $this->razon_social = $razon_social;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(?string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(?string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * @return Collection|Factura[]
     */
    public function getFacturas(): Collection
    {
        return $this->facturas;
    }

    public function addFactura(Factura $factura): self
    {
        if (!$this->facturas->contains($factura)) {
            $this->facturas[] = $factura;
            $factura->setCliente($this);
        }

        return $this;
    }

    public function removeFactura(Factura $factura): self
    {
        if ($this->facturas->contains($factura)) {
            $this->facturas->removeElement($factura);
            // set the owning side to null (unless already changed)
            if ($factura->getCliente() === $this) {
                $factura->setCliente(null);
            }
        }

        return $this;
    }
}

src/Entity/Factura.php
<?php

namespace App\Entity;

use App\Repository\FacturaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FacturaRepository::class)
 */
class Factura
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $establecimiento;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $punto_emision;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sec_factura;

    /**
     * @ORM\ManyToOne(targetEntity=Empresa::class, inversedBy="facturas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $empresa;

    /**
     * @ORM\ManyToOne(targetEntity=Cliente::class, inversedBy="facturas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $cliente;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha;

    /**
     * @ORM\OneToMany(targetEntity=DetalleFactura::class, mappedBy="factura", orphanRemoval=true)
     */
    private $detalleFacturas;

    /**
     * @ORM\Column(type="float")
     */
    private $subtotal;

    /**
     * @ORM\Column(type="float")
     */
    private $impuestos;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    public function __construct()
    {
        $this->detalleFacturas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEstablecimiento(): ?string
    {
        return $this->establecimiento;
    }

    public function setEstablecimiento(string $establecimiento): self
    {
        $this->establecimiento = $establecimiento;

        return $this;
    }

    public function getPuntoEmision(): ?string
    {
        return $this->punto_emision;
    }

    public function setPuntoEmision(string $punto_emision): self
    {
        $this->punto_emision = $punto_emision;

        return $this;
    }

    public function getSecFactura(): ?string
    {
        return $this->sec_factura;
    }

    public function setSecFactura(string $sec_factura): self
    {
        $this->sec_factura = $sec_factura;

        return $this;
    }

    public function getEmpresa(): ?Empresa
    {
        return $this->empresa;
    }

    public function setEmpresa(?Empresa $empresa): self
    {
        $this->empresa = $empresa;

        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): self
    {
        $this->cliente = $cliente;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    /**
     * @return Collection|DetalleFactura[]
     */
    public function getDetalleFacturas(): Collection
    {
        return $this->detalleFacturas;
    }

    public function addDetalleFactura(DetalleFactura $detalleFactura): self
    {
        if (!$this->detalleFacturas->contains($detalleFactura)) {
            $this->detalleFacturas[] = $detalleFactura;
            $detalleFactura->setFactura($this);
        }

        return $this;
    }

    public function removeDetalleFactura(DetalleFactura $detalleFactura): self
    {
        if ($this->detalleFacturas->contains($detalleFactura)) {
            $this->detalleFacturas->removeElement($detalleFactura);
            // set the owning side to null (unless already changed)
            if ($detalleFactura->getFactura() === $this) {
                $detalleFactura->setFactura(null);
            }
        }

        return $this;
    }

    public function getSubtotal(): ?float
    {
        return $this->subtotal;
    }

    public function setSubtotal(float $subtotal): self
    {
        $this->subtotal = $subtotal;

        return $this;
    }

    public function getImpuestos(): ?float
    {
        return $this->impuestos;
    }

    public function setImpuestos(float $impuestos): self
    {
        $this->impuestos = $impuestos;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }
}

src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Repository\ProductoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductoRepository::class)
 */
class Producto
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $codigo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $detalle;

    /**
     * @ORM\Column(type="float")
     */
    private $precio_unit;

    /**
     * @ORM\OneToMany(targetEntity=DetalleFactura::class, mappedBy="producto")
     */
    private $detalleFacturas;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\Column(type="boolean")
     */
    private $impuesto;

    public function __construct()
    {
        $this->detalleFacturas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    public function setCodigo(string $codigo): self
    {
        $this->codigo = $codigo;

        return $this;
    }

    public function getDetalle(): ?string
    {
        return $this->detalle;
    }

    public function setDetalle(string $detalle): self
    {
        $this->detalle = $detalle;

        return $this;
    }

    public function getPrecioUnit(): ?float
    {
        return $this->precio_unit;
    }

    public function setPrecioUnit(float $precio_unit): self
    {
        $this->precio_unit = $precio_unit;

        return $this;
    }

    /**
     * @return Collection|DetalleFactura[]
     */
    public function getDetalleFacturas(): Collection
    {
        return $this->detalleFacturas;
    }

    public function addDetalleFactura(DetalleFactura $detalleFactura): self
    {
        if (!$this->detalleFacturas->contains($detalleFactura)) {
            $this->detalleFacturas[] = $detalleFactura;
            $detalleFactura->setProducto($this);
        }

        return $this;
    }

    public function removeDetalleFactura(DetalleFactura $detalleFactura): self
    {
        if ($this->detalleFacturas->contains($detalleFactura)) {
            $this->detalleFacturas->removeElement($detalleFactura);
            // set the owning side to null (unless already changed)
            if ($detalleFactura->getProducto() === $this) {
                $detalleFactura->setProducto(null);
            }
        }

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getImpuesto(): ?bool
    {
        return $this->impuesto;
    }

    public function setImpuesto(bool $impuesto): self
    {
        $this->impuesto = $impuesto;

        return $this;
    }
}

templates/facturacion/clientes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clientes{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<style type="text/css">
    .nav-link{font-size:20px !important;}
    .btn-success{margin-top: 30px;}
    .div-btn{text-align: end;}
    #msjError{background-color: #ffe4e4; margin:10px;padding:10px; width: 100%;color:red;}
    .imp{font-size: 20px;}
</style>
{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mx-auto" style="font-size:10px">
        <li class="nav-item">
            <a href="/facturacion" class="nav-link"><span data-hover="Facturas">Facturas</span></a>
        </li>
        <li class="nav-item">
            <a href="/clientes" class="nav-link"><span style="color:#ffc200" data-hover="Clientes">Clientes</span></a>
        </li>
        <li class="nav-item">
            <a href="/empresas" class="nav-link"><span data-hover="Empresas">Empresas</span></a>
        </li>
        <li class="nav-item">
            <a href="/productos" class="nav-link"><span  data-hover="Productos">Productos</span></a>
        </li>
        <li class="nav-item">
            <a href="/configuracion" class="nav-link"><span data-hover="Configuracion">Configuracion</span></a>
        </li>
        <li class="nav-item">
            <a href="/logout" class="nav-link"><span data-hover="LogOut">Logout</span></a>
        </li>
    </ul>
</div>
{% endblock %}


{% block body %}
<section class="sample-text-area" style="margin-top: 40px;">
    <div class="container box_1170">
        <div class="row">
            <div class="col-6"><h1><i class="fas fa-user-tie"></i> Clientes</h1></div>
            <div class="col-6 div-btn">
                <button type="button" class="btn btn-success" onclick="abrirModalForm('nuevo', 0)">
                    <i class="fas fa-plus"></i> Agregar Nuevo Cliente
                </button>
            </div>
        </div>
        <table id="tabla-clientes" class="display" style="width:100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>RUC / CI</th>
                    <th>Razon Social</th>
                    <th>telefono</th>
                    <th>direccion</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
              {% for cliente in clientes %}
                  <tr>
                    <td><span class="id-cliente" value="{{ cliente.id }}">{{ cliente.id }}</span></td>
                    <td>{{ cliente.ciRuc }}</td>
                    <td>{{ cliente.razonSocial }}</td>
                    <td>{{ cliente.telefono }}</td>
                    <td>{{ cliente.direccion }}</td>
                    <td>
                      <button type="button" class="btn btn-secondary btn-editar" value="{{ cliente.id }}">
                        <i class="fas fa-pen"></i>
                      </button>
                      <button type="button" class="btn btn-danger btn-eliminar" value="{{ cliente.id }}">
                        <i class="fas fa-times"></i>
                      </button>
                    </td>
                  </tr>
              {% endfor %}               
            </tbody>
        </table>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="ModalForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="Modaltitulo">Nuevo Cliente</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form>
          <div class="modal-body">
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="ruc">RUC / CI</label>
                  <input type="text" class="form-control" id="ruc" required="required">
                </div>
                <div class="form-group col-md-6">
                  <label for="telefono">Telefono</label>
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text"><i class="fas fa-phone-alt"></i></div>
                    </div>
                    <input type="text" class="form-control" id="telefono" required="required">
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="razonSocial">Razon Social</label>
                  <input type="text" class="form-control" id="razonSocial" placeholder="" required="required">
                </div>
                <div class="form-group col-md-6">
                  <label for="direccion">direccion</label>
                  <input type="text" class="form-control" id="direccion" required="required">
                </div>
              </div>
              <div class="form-row error" style="display:none">
                  <span id="msjError"><i class="fas fa-exclamation-circle"></i><span id="msje"></span></span>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <button type="button" class="btn btn-primary" id="btn-modal-form" onclick="nuevoCliente()">Guardar</button>
          </div>
      </form>
    </div>
  </div>
</div>


<div class="modal" id="Advertencia" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Se va a eliminar un Cliente</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Esta seguro que desea continuar?.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger eliminar-definitivo" data-dismiss="modal" value="0" >Eliminar Cliente</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block javascripts %}


<script type="text/javascript">

    $(document).ready(function() 
    {
        $('#tabla-clientes').DataTable( {
            "language": {
                url: 'https://cdn.datatables.net/plug-ins/1.10.21/i18n/Spanish.json'
            },
            "order": [[ 0, "desc" ]]
        });

      $(document).on('click', '.btn-eliminar', function(){
          id = $(this).attr("value");
          alertaEliminar(id);
      });

      $(".eliminar-definitivo").click(function(){
          id = $(this).attr("value");
          eliminarCliente(id);
      });

      $(document).on('click', '.btn-editar', function(){
          id = $(this).attr("value");
          abrirModalForm('editar', id);
      });
    } );



</script>
<script src="/js/clientes.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
{% endblock %}

templates/facturacion/pdfTemplate.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>Factura</title>
</head>
<body>

<section class="sample-text-area" style="margin-top: 40px;">
    <div class="container box_1170">
        
        <br>
        <div class="row">

            <div class="col-sm-8 offset-sm-2" style="border: 1px solid; padding: 30px">
                <div class="row">
                    <div class="col-sm-12">
                        
                    </div>
                </div>
                <table style="width:100%">
                    <tr>
                        <td>
                            <h2>{{ factura.empresa.razonSocial }}</h2>
                            <div><span>RUC: {{ factura.empresa.ruc }}</span></div>
                            <div><span>{{ factura.empresa.direccion }}</span></div>
                                

                        </td>
                        <td>
                            <div><span><b>No de Factura</b></span></div>
                            <div><span>{{ factura.establecimiento }}-{{ factura.puntoEmision }}-{{ factura.secFactura }}</span></div><br>
                            <div><span><b>Fecha Emision</b></span></div>
                            <div><span>{{ factura.fecha|date("d/m/Y") }}</span></div>
                        </td>
                    </tr>
                </table>
                <br>
                <div><span><h4 style="margin-bottom:10px; margin-top:10px">Cliente</h4></span></div>
                <table style="width:100%">
                    <tr>
                        <td width="100px"><div class="col-sm-3"><b>Razon social</b></div></td>
                        <td><div class="col-sm-9">{{ factura.cliente.razonSocial }}</div></td>
                    </tr>
                    <tr>
                        <td><div class="col-sm-3"><b>CI/RUC</b></div></td>
                        <td><div class="col-sm-9">{{ factura.cliente.ciRuc }}</div></td>
                    </tr>
                     <tr>
                        <td><div class="col-sm-3"><b>Direccion</b></div></td>
                        <td><div class="col-sm-9">{{ factura.cliente.direccion }}</div></td>
                    </tr>
                     <tr>
                        <td><div class="col-sm-3"><b>Telefono</b></div></td>
                        <td><div class="col-sm-9">{{ factura.cliente.telefono }}</div></td>
                    </tr>
                </table>


                <br>
                <div class="row">
                    <div class="col-md-12"><span><h3>Detalle</h3></span></div>
                    <table style="width:100%; border-collapse: collapse; border:1px solid">
                        <tr>
                            <td style="border:1px solid; padding:5px; text-align:center"><b>Producto</b></td>
                            <td style="border:1px solid; padding:5px; text-align:center"><b>Precio Unit.</b></td>
                            <td style="border:1px solid; padding:5px; text-align:center"><b>Cantidad</b></td>
                            <td style="border:1px solid; padding:5px; text-align:center"><b>SubTotal</b></td>
                        </tr>
                        {% for detalle in detalles %}
                        <tr>
                            <td style="border:1px solid; padding:5px;">$ {{ detalle.producto.detalle }}</td>
                            <td style="border:1px solid; padding:5px;">{{ detalle.producto.precioUnit }}</td>
                            <td style="border:1px solid; padding:5px;">$ {{ detalle.cantidad }}</td>
                            {% set subtotal =  detalle.producto.precioUnit  *  detalle.cantidad  %}
                            <td style="border:1px solid; padding:5px; text-align:right">{{ subtotal }}</td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td style="padding:5px;"></td>
                            <td style="padding:5px;"></td>
                            <td style="border:1px solid;padding:5px;text-align:right"><b>Subtotal</b></td>
                            <td style="border:1px solid;padding:5px;text-align:right">${{ factura.subtotal }}</td>
                        </tr>
                        <tr>
                            <td style="padding:5px;"></td>
                            <td style="padding:5px;"></td>
                            <td style="border:1px solid;padding:5px;text-align:right"><b>Impuestos</b></td>
                            <td style="border:1px solid;padding:5px;text-align:right">${{ factura.impuestos }}</td>
                        </tr>
                        <tr>
                            <td style="padding:5px;"></td>
                            <td style="padding:5px;"></td>
                            <td style="border:1px solid;padding:5px;text-align:right"><b>Total</b></td>
                            <td style="border:1px solid;padding:5px;text-align:right">${{ factura.total }}</td>
                        </tr>
                    </table>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>

    </div>
    
</section>

</body>
</html>>

templates/facturacion/revisarFactura.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factura{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"
>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

<style type="text/css">
    .nav-link{font-size:20px !important;}
    .dataTables_filter {display: none;}
    .btn-top{margin-top: 30px;}
    .div-btn{text-align: end;}
    #msjError{background-color: #ffe4e4; margin:10px;padding:10px; width: 100%;color:red;}
    .imp{font-size: 20px;}
    .bootstrap-select{width:100% !important;}
    .factTitulo{text-align: right;}
    .number{text-align: right;}
    .registros{border-bottom: 1px solid;}
    .eliminarRow{color: red;font-size: 22px;}
    .btn-outline-danger{border-color: #fafafa  !important;}
    .gris{background-color: #ebebeb}
</style>
{% endblock %}

{% block menu %}

<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mx-auto" style="font-size:10px">
        <li class="nav-item">
            <a href="/facturacion" class="nav-link"><span style="color:#ffc200" data-hover="Facturas">Facturas</span></a>
        </li>
        <li class="nav-item">
            <a href="/clientes" class="nav-link"><span data-hover="Clientes">Clientes</span></a>
        </li>
        <li class="nav-item">
            <a href="/empresas" class="nav-link"><span data-hover="Empresas">Empresas</span></a>
        </li>
        <li class="nav-item">
            <a href="/productos" class="nav-link"><span data-hover="Productos">Productos</span></a>
        </li>
        <li class="nav-item">
            <a href="/configuracion" class="nav-link"><span data-hover="Configuracion">Configuracion</span></a>
        </li>
        <li class="nav-item">
            <a href="/logout" class="nav-link"><span data-hover="LogOut">Logout</span></a>
        </li>
    </ul>
</div>
{% endblock %}


{% block body %}

<section class="sample-text-area" style="margin-top: 40px;">
	<div class="container box_1170">
		
        <div class="row">
            <div class="col-8"><h3><i class="fas fa-file-invoice"></i> FACTURA N {{ factura.establecimiento }}-{{ factura.puntoEmision }}-{{ factura.secFactura }}</h3></div>
            <div class="col-4 div-btn">
                <button type="button" class="btn btn-info btn-imprimir" >
                    <i class="fas fa-print"></i> IMPRIMIR
                </button>
            </div>
        </div>
        <br>
        <div class"row">
            <div class="col-sm-8 offset-sm-2" style="border: 1px solid; padding: 30px">
                <div class="row">
                    <div class="col-sm-12">
                        <h5>{{ factura.empresa.razonSocial }}</h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <div><span>RUC: {{ factura.empresa.ruc }}</span></div>
                        <div><span>{{ factura.empresa.direccion }}</span></div>
                    </div>
                    <div class="col-sm-4">
                        <div><span><b>No de Factura</b></span></div>
                        <div><span>{{ factura.establecimiento }}-{{ factura.puntoEmision }}-{{ factura.secFactura }}</span></div>
                        <div><span><b>Fecha Emision</b></span></div>
                        <div><span>{{ factura.fecha|date("d/m/Y") }}</span></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div><span><h5>Cliente</h5></span></div>
                        <div class="row">
                            <div class="col-sm-3"><b>Razon social</b></div>
                            <div class="col-sm-9">{{ factura.cliente.razonSocial }}</div>
                        </div>
                        <div class="row gris">
                            <div class="col-sm-3"><b>CI/RUC</b></div>
                            <div class="col-sm-9">{{ factura.cliente.ciRuc }}</div>
                        </div>
                        <div class="row ">
                            <div class="col-sm-3"><b>Direccion</b></div>
                            <div class="col-sm-9">{{ factura.cliente.direccion }}</div>
                        </div>
                        <div class="row gris">
                            <div class="col-sm-3"><b>Telefono</b></div>
                            <div class="col-sm-9">{{ factura.cliente.telefono }}</div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-md-12"><span><h5>Detalle</h5></span></div>
                    <div class="col-md-12">
                        <div class="row registros">
                            <div class="form-group col-md-5"><b>Producto</b></div>
                            <div class="form-group col-md-2 number"><b>Precio Unit</b></div>
                            <div class="form-group col-md-2 number"><b>Cantidad</b></div>
                            <div class="form-group col-md-2 number"><b>SubTotal</b></div>
                            <div class="form-group col-md-1"></div>
                        </div>
                    </div>
                    {% for detalle in detalles %}
                    <div class="col-md-12">
                        <div class="row registros">
                            <div class="form-group col-md-5">{{ detalle.producto.detalle }}</div>
                            <div class="form-group col-md-2 number">{{ detalle.producto.precioUnit }}</div>
                            <div class="form-group col-md-2 number">{{ detalle.cantidad }}</div>
                            {% set subtotal =  detalle.producto.precioUnit  *  detalle.cantidad  %}
                            <div class="form-group col-md-2 number">{{ subtotal }}</div>
                            <div class="form-group col-md-1"></div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col-md-12">
                        <div class="row">
                            <div class="form-group col-md-2 offset-sm-7 factTitulo"><b>SubTotal:</b></div>
                            <div id="valor-subtotal" class="form-group col-md-2 factTitulo">${{ factura.subtotal }}</div>
                        </div>

                      </div>
                      <div class="col-md-12">
                        <div class="row">
                            <div class="form-group col-md-2 offset-sm-7 factTitulo"><b>Impuesto:</b></div>
                            <div id="valor-impuesto"  class="form-group col-md-2 factTitulo">${{ factura.impuestos }}</div>
                        </div>
                      </div>
                      <div class="col-md-12">
                        <div class="row">
                            <div class="form-group col-md-2 offset-sm-7 factTitulo"><b>TOTAL:</b></div>
                            <div id="valor-total" class="form-group col-md-2 factTitulo">${{ factura.total }}</div>
                        </div>
                      </div>
                </div>
            </div>
        </div>

	</div>
    
</section>



{% endblock %}

{% block javascripts %}


<script type="text/javascript">
	$(document).ready(function() {

        $('.btn-imprimir').on('click', function(){
            $(location).attr('href', '/facturacion/cod{{ factura.id }}/imprimir');

        });
        
	} );

</script>

<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>



{% endblock %}

templates/facturacion/test.html.twig
{{ title }}